### ISSUE TITLE
About Active Score

### ISSUE THREAD

**Issue by yuanlonghui** [thuml/Transferable-Query-Selection#3]
Hello, thank you for your great work. However, I found some bugs here. 
The active score actually used in the released code is the sum of transferable committee and uncetainty, https://github.com/thuml/Transferable-Query-Selection/blob/73fa889ecb074509bca9c0a272863fe24e0f13fd/code/main.py#L169 form which the propoesed domainness is absent. And the optional active score in the the comment line uses the output of the domain discriminator as the domainness,
https://github.com/thuml/Transferable-Query-Selection/blob/73fa889ecb074509bca9c0a272863fe24e0f13fd/code/main.py#L166 https://github.com/thuml/Transferable-Query-Selection/blob/73fa889ecb074509bca9c0a272863fe24e0f13fd/code/main.py#L168 which isn't consistent with the domainness in the article. In the article, the domainness is the value of a Gaussion distribution funciton with the output of the domain discriminator.

**Comment by microhhh** [comment]
Thank you very much. 
The release version of the code is still in progress, please wait.
