### ISSUE TITLE
Where can I find committee loss on the code?

### ISSUE THREAD

**Issue by sehyun03** [thuml/Transferable-Query-Selection#5]
Thank you for the work!

I could not find committee loss (equation (1) in your paper) in the script.

Where can I find committee loss which utilizes perturbed features for reducing randomness?

It seems that equation (1) is one of the main contributions to make selection transferable.

Also, if this part of the implementation has not been added, do you have any plans to complete it?

**Comment by microhhh** [comment]
Equation 1 mainly talks about maximizing the difference. The consistency loss is implicit. We can apply the same label to multiple classifiers, which has been reflected in the training process.
