### ISSUE TITLE
Hi, could you release the final version code?

### ISSUE THREAD

**Issue by xutting123** [thuml/Transferable-Query-Selection#6]
Hello, thank you for your great work. Could you please provide the code of the final version? In the current version, some key issues in the paper (such as the discrimiantor and gaussian distribution) are not implemented, which makes it difficult to reproduce. Looking forward to your reply.

**Comment by microhhh** [comment]
The calculation of gaussian distribution is slow, so I simplified to a linear version and speeds up the computation of other criteria, the accuracy is almost constant.
